#!/bin/sh
# manage applications via apt, persisted to devysix.toml
DEVYSIX_CONFIG="${DEVYSIX_CONFIG:-/etc/devysix/devysix.toml}"

action="$1"
shift

case "$action" in
    install)   apt install "$@" ;;
    remove)    apt remove "$@" ;;
    search)    apt search "$@" ;;
    list)      apt list --installed 2>/dev/null ;;
    *)
        echo "usage: dev apps <install|remove|search|list> [packages]" >&2
        exit 1
        ;;
esac
